name: gen
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  icon_font_generator: ^4.0.0
  analyzer: ^6.4.1
  glob: ^2.1.3
  file: ^7.0.1
  archive: ^4.0.7

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
